name: Semgrep CLI Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Semgrep x semgrep-rules-manager
        uses: iosifache/semgrep-rules-manager@release
